version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.2-3.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  php:
    image: wodby/drupal-php:7.1-4.2.2
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - ./drupal:/var/www/drupal:cached
      - ./dump:/var/www/dump:cached
      - .git:/var/www/.git:cached
      - ./spin-up.sh:/var/www/html/spin-up.sh

  nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/drupal/docroot
    volumes:
      - ./drupal:/var/www/drupal:cached
    ports:
      - 80:80

  react:
    build:
      context: ./react
      dockerfile: Dockerfile-react
    command: npm start
    environment:
      DRUPAL_URL: http://nginx
      DRUPAL_USER: apitest
      DRUPAL_PASSWORD: apitest
      CLIENT_SECRET: apitest
      CLIENT_ID: be2557eb-bd73-4606-9a45-30b94a07019d
    volumes:
      - ./react/code:/usr/app/
      - ./react/.env.react:/usr/app/.env
      - /usr/app/node_modules
    depends_on:
      - php
      - nginx
    ports:
      - 8080:8080

  graphql:
    build:
      context: ./react
      dockerfile: Dockerfile-graphql
    command: npm start
    environment:
      API_PUBLIC_KEY: put_your_marvel_public_key
      API_PRIVATE_KEY: put_your_marvel_private_key
      APOLLO_ENGINE: put_your_apolo_engine_key
      DRUPAL_URL: http://nginx
      PORT: 8082
      MOCK: 'TRUE'
      DRUPAL_USER: apitest
      DRUPAL_PASSWORD: apitest
      CLIENT_SECRET: apitest
      CLIENT_ID: be2557eb-bd73-4606-9a45-30b94a07019d
    volumes:
      - ./react/code/__graphql_server:/usr/app/
      - ./react/.env.graphql:/usr/app/.env
      - /usr/app/node_modules
    depends_on:
      - php
      - nginx
    ports:
      - 8082:8082

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.decoupledkit.com'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.decoupledkit.com'

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.decoupledkit.com'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
